N_QUBITS = 1024
VERBOSE = True
EVE_IS_PRESENT = False
EVE_IS_INTERFERING = False
CIPHER = 'AES' # AES or OTP

ALICE_CLASSICAL_RECIPIENT = "Bob"
BOB_CLASSICAL_RECIPIENT= "Alice"

if EVE_IS_PRESENT:
    ALICE_QUANTUM_RECIPIENT = "Eve"
else:
    ALICE_QUANTUM_RECIPIENT = "Bob"
